#ifndef _TX_FUNCTIONS_HPP
#define _TX_FUNCTIONS_HPP

#include "../set_tx_subdev_spec.hpp"
#include "../get_tx_subdev_spec.hpp"
#include "../get_tx_num_channels.hpp"
#include "../get_tx_subdev_name.hpp"
#include "../set_tx_rate.hpp"
#include "../get_tx_rate.hpp"
#include "../get_tx_rates.hpp"
#include "../set_tx_freq.hpp"
#include "../get_tx_freq.hpp"
#include "../get_tx_freq_range.hpp"
#include "../get_fe_tx_freq_range.hpp"
#include "../set_tx_freq.hpp"
#include "../get_tx_freq.hpp"
#include "../get_tx_freq_range.hpp"
#include "../get_fe_tx_freq_range.hpp"
#include "../set_tx_gain.hpp"
#include "../get_tx_gain_names.hpp"
#include "../get_tx_gain_profile_names.hpp"
#include "../set_tx_gain_profile.hpp"
#include "../get_tx_gain_profile.hpp"
#include "../get_tx_gain.hpp"
#include "../set_tx_gain.hpp"
#include "../set_normalized_tx_gain.hpp"
#include "../get_tx_gain.hpp"
#include "../get_normalized_tx_gain.hpp"
#include "../get_tx_gain_range.hpp"
#include "../get_tx_gain_names.hpp"
#include "../set_tx_antenna.hpp"
#include "../get_tx_antenna.hpp"
#include "../get_tx_antennas.hpp"
#include "../set_tx_bandwidth.hpp"
#include "../get_tx_bandwidth.hpp"
#include "../get_tx_bandwidth_range.hpp"
#include "../create_tx_dboard_iface.hpp"
#include "../get_tx_sensor.hpp"
#include "../get_tx_sensor_names.hpp"
#include "../set_tx_dc_offset.hpp"
#include "../get_tx_dc_offset_range.hpp"
#include "../set_tx_iq_balance.hpp"

#endif // !_TX_FUNCTIONS_HPP


